version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: developerstore_db
    environment:
      - POSTGRES_USER=storeuser
      - POSTGRES_PASSWORD=storeuser123
      - POSTGRES_DB=store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
